# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_bar = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_bar.setGeometry(QtCore.QRect(10, 0, 981, 701))
        self.tab_bar.setObjectName("tab_bar")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 981, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pText_list = QtWidgets.QPlainTextEdit(self.frame)
        self.pText_list.setEnabled(True)
        self.pText_list.setGeometry(QtCore.QRect(10, 220, 961, 281))
        self.pText_list.setReadOnly(True)
        self.pText_list.setObjectName("pText_list")
        self.btn_connect = QtWidgets.QPushButton(self.frame)
        self.btn_connect.setGeometry(QtCore.QRect(10, 10, 94, 32))
        self.btn_connect.setObjectName("btn_connect")
        self.btn_info = QtWidgets.QPushButton(self.frame)
        self.btn_info.setGeometry(QtCore.QRect(870, 10, 94, 32))
        self.btn_info.setObjectName("btn_info")
        self.pText_info = QtWidgets.QPlainTextEdit(self.frame)
        self.pText_info.setEnabled(True)
        self.pText_info.setGeometry(QtCore.QRect(10, 70, 961, 141))
        self.pText_info.setReadOnly(True)
        self.pText_info.setObjectName("pText_info")
        self.tab_bar.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pText_dtc = QtWidgets.QPlainTextEdit(self.tab_2)
        self.pText_dtc.setEnabled(True)
        self.pText_dtc.setGeometry(QtCore.QRect(10, 130, 971, 361))
        self.pText_dtc.setReadOnly(True)
        self.pText_dtc.setObjectName("pText_dtc")
        self.btn_read_dtc = QtWidgets.QPushButton(self.tab_2)
        self.btn_read_dtc.setGeometry(QtCore.QRect(10, 10, 94, 32))
        self.btn_read_dtc.setObjectName("btn_read_dtc")
        self.btn_clear_dtc = QtWidgets.QPushButton(self.tab_2)
        self.btn_clear_dtc.setGeometry(QtCore.QRect(880, 10, 94, 32))
        self.btn_clear_dtc.setObjectName("btn_clear_dtc")
        self.tab_bar.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_bar.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pText_debug = QtWidgets.QPlainTextEdit(self.tab_4)
        self.pText_debug.setEnabled(True)
        self.pText_debug.setGeometry(QtCore.QRect(10, 150, 961, 351))
        self.pText_debug.setReadOnly(True)
        self.pText_debug.setObjectName("pText_debug")
        self.tab_bar.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_bar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_connect.setText(_translate("MainWindow", "Conectar"))
        self.btn_info.setText(_translate("MainWindow", "Info"))
        self.tab_bar.setTabText(self.tab_bar.indexOf(self.tab), _translate("MainWindow", "Principal"))
        self.btn_read_dtc.setText(_translate("MainWindow", "Leitura DTC"))
        self.btn_clear_dtc.setText(_translate("MainWindow", "Limpa DTC"))
        self.tab_bar.setTabText(self.tab_bar.indexOf(self.tab_2), _translate("MainWindow", "DTC"))
        self.tab_bar.setTabText(self.tab_bar.indexOf(self.tab_3), _translate("MainWindow", "Analogicos"))
        self.tab_bar.setTabText(self.tab_bar.indexOf(self.tab_4), _translate("MainWindow", "Debug"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
